<a href="https://colab.research.google.com/github/Mohammad-Moradi1/py-torch-training/blob/main/py_torch_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch torchvision

# کار با تنسورها (Tensors)

In [3]:
import torch

x = torch.tensor([1.0 , 2.0 , 3.0])
print(x)
print(type(x))

tensor([1., 2., 3.])
<class 'torch.Tensor'>


In [5]:
random_tensor = torch.rand(4 , 4)
print(random_tensor)

tensor([[0.4440, 0.4862, 0.2802, 0.2592],
        [0.2070, 0.1646, 0.8847, 0.9165],
        [0.2950, 0.1793, 0.2634, 0.2296],
        [0.3117, 0.0608, 0.8096, 0.1955]])


In [6]:
zeros_tensor = torch.zeros(3 , 3)
ones_tensor = torch.ones(3,3)

print(zeros_tensor)
print(ones_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [8]:
line_space = torch.linspace(0,1,steps = 5)
print(line_space)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [13]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print(a + b)
print(a * b)

# ماتریس ضرب
mat1 = torch.rand(2, 3)
mat2 = torch.rand(3, 2)
result = torch.matmul(mat1, mat2)  # ضرب ماتریسی
print(result)

# عملیات‌های پیشرفته
mean = a.mean()
std = a.std()
print(mean)
print(std)

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor([[0.4708, 0.2827],
        [0.7786, 0.2456]])
tensor(2.)
tensor(1.)


#استفاده از *GPU*

In [14]:
# بررسی دسترسی GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cpu


In [16]:
# انتقال تنسور به GPU
a_tensor = torch.rand(3, 3)
tensor_gpu = a_tensor.to(device)
print(tensor_gpu)

tensor([[5.0008e-01, 9.6132e-01, 4.0790e-01],
        [2.4758e-01, 3.1745e-04, 8.1258e-01],
        [1.4393e-01, 7.5865e-01, 9.0755e-01]])


#  Autograd: محاسبه گرادیان‌ها

In [21]:
# ایجاد یک تنسور با قابلیت گرادیان
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3 * x + 4  # تابع
y.backward()  # محاسبه گرادیان
print(x.grad)  # گرادیان: dy/dx

tensor(7.)


# ساخت یک مدل ساده شبکه عصبی

In [26]:
#ایجاد یک مدل ساده
import torch.nn as nn

# تعریف یک شبکه ساده
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc = nn.Linear(1, 1)  # لایه کاملاً متصل

    def forward(self, x):
        return self.fc(x)

# نمونه‌سازی مدل
model = SimpleNN()
print(model)

SimpleNN(
  (fc): Linear(in_features=1, out_features=1, bias=True)
)


In [27]:
#تابع هزینه و بهینه‌سازی

import torch.optim as optim

# تعریف تابع هزینه و بهینه‌ساز
criterion = nn.MSELoss()  # Mean Squared Error
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [32]:
# آموزش مدل

# داده‌های آموزشی ساده
x_train = torch.tensor([[1.0], [2.0], [3.0]])
y_train = torch.tensor([[2.0], [4.0], [6.0]])

# حلقه آموزشی
for epoch in range(100):
    # مرحله پیش‌بینی
    y_pred = model(x_train)

    # محاسبه هزینه
    loss = criterion(y_pred, y_train)

    # به‌روزرسانی مدل
    optimizer.zero_grad()  # صفر کردن گرادیان‌ها
    loss.backward()  # محاسبه گرادیان
    optimizer.step()  # به‌روزرسانی وزن‌ها

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

Epoch 0, Loss: 0.09513166546821594
Epoch 10, Loss: 0.09066084772348404
Epoch 20, Loss: 0.0864000990986824
Epoch 30, Loss: 0.0823395773768425
Epoch 40, Loss: 0.0784699097275734
Epoch 50, Loss: 0.07478218525648117
Epoch 60, Loss: 0.07126769423484802
Epoch 70, Loss: 0.06791842728853226
Epoch 80, Loss: 0.06472652405500412
Epoch 90, Loss: 0.06168454885482788


# ذخیره و بارگذاری مدل

In [33]:
torch.save(model.state_dict() , "simple_nn.path")

In [34]:
model = SimpleNN()
model.load_state_dict(torch.load("simple_nn.pth"))
model.eval()  # تغییر مدل به حالت ارزیابی

<ipython-input-34-6f41352d23e4>:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load("simple_nn.path"))


SimpleNN(
  (fc): Linear(in_features=1, out_features=1, bias=True)
)