<a href="https://colab.research.google.com/github/Mohammad-Moradi1/py-torch-training/blob/main/py_torch_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install torch torchvision

# کار با تنسورها (Tensors)

In [3]:
import torch

x = torch.tensor([1.0 , 2.0 , 3.0])
print(x)
print(type(x))

tensor([1., 2., 3.])
<class 'torch.Tensor'>


In [4]:
random_tensor = torch.rand(4 , 4)
print(random_tensor)

tensor([[0.3952, 0.3273, 0.9671, 0.6146],
        [0.8896, 0.9818, 0.1164, 0.3402],
        [0.8139, 0.9244, 0.4854, 0.4808],
        [0.5849, 0.6935, 0.0423, 0.2206]])


In [5]:
zeros_tensor = torch.zeros(3 , 3)
ones_tensor = torch.ones(3,3)

print(zeros_tensor)
print(ones_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [6]:
line_space = torch.linspace(0,1,steps = 5)
print(line_space)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [7]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print(a + b)
print(a * b)

# ماتریس ضرب
mat1 = torch.rand(2, 3)
mat2 = torch.rand(3, 2)
result = torch.matmul(mat1, mat2)  # ضرب ماتریسی
print(result)

# عملیات‌های پیشرفته
mean = a.mean()
std = a.std()
print(mean)
print(std)

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor([[0.8305, 0.4273],
        [0.2945, 0.8394]])
tensor(2.)
tensor(1.)


#استفاده از *GPU*

In [8]:
# بررسی دسترسی GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cpu


In [9]:
# انتقال تنسور به GPU
a_tensor = torch.rand(3, 3)
tensor_gpu = a_tensor.to(device)
print(tensor_gpu)

tensor([[0.3493, 0.4288, 0.9376],
        [0.2304, 0.3361, 0.8463],
        [0.0464, 0.9448, 0.1263]])


#  Autograd: محاسبه گرادیان‌ها

In [10]:
# ایجاد یک تنسور با قابلیت گرادیان
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3 * x + 4  # تابع
y.backward()  # محاسبه گرادیان
print(x.grad)  # گرادیان: dy/dx

tensor(7.)


# ساخت یک مدل ساده شبکه عصبی

In [11]:
#ایجاد یک مدل ساده
import torch.nn as nn

# تعریف یک شبکه ساده
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc = nn.Linear(1, 1)  # لایه کاملاً متصل

    def forward(self, x):
        return self.fc(x)

# نمونه‌سازی مدل
model = SimpleNN()
print(model)

SimpleNN(
  (fc): Linear(in_features=1, out_features=1, bias=True)
)


In [12]:
#تابع هزینه و بهینه‌سازی

import torch.optim as optim

# تعریف تابع هزینه و بهینه‌ساز
criterion = nn.MSELoss()  # Mean Squared Error
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [13]:
# آموزش مدل

# داده‌های آموزشی ساده
x_train = torch.tensor([[1.0], [2.0], [3.0]])
y_train = torch.tensor([[2.0], [4.0], [6.0]])

# حلقه آموزشی
for epoch in range(100):
    # مرحله پیش‌بینی
    y_pred = model(x_train)

    # محاسبه هزینه
    loss = criterion(y_pred, y_train)

    # به‌روزرسانی مدل
    optimizer.zero_grad()  # صفر کردن گرادیان‌ها
    loss.backward()  # محاسبه گرادیان
    optimizer.step()  # به‌روزرسانی وزن‌ها

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

Epoch 0, Loss: 26.78191566467285
Epoch 10, Loss: 2.8881845474243164
Epoch 20, Loss: 0.5971534848213196
Epoch 30, Loss: 0.36386361718177795
Epoch 40, Loss: 0.32722190022468567
Epoch 50, Loss: 0.3099830448627472
Epoch 60, Loss: 0.29523777961730957
Epoch 70, Loss: 0.28134605288505554
Epoch 80, Loss: 0.2681220471858978
Epoch 90, Loss: 0.2555212080478668


# ذخیره و بارگذاری مدل

In [17]:
torch.save(model.state_dict() , "simple_nn.path")

In [19]:
model = SimpleNN()
model.load_state_dict(torch.load("simple_nn.path"))
model.eval()  # تغییر مدل به حالت ارزیابی

<ipython-input-19-440c5660f419>:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load("simple_nn.path"))


SimpleNN(
  (fc): Linear(in_features=1, out_features=1, bias=True)
)

# محاسبه مشتق دوم

In [20]:
x = torch.tensor(2.0, requires_grad=True)

# تعریف تابع
y = x**3  # y = x^3

# محاسبه گرادیان اول
y.backward(create_graph=True)
print("First derivative (dy/dx):", x.grad)

# محاسبه گرادیان دوم
x.grad.zero_()  # صفر کردن گرادیان‌ها
x.grad.backward()  # محاسبه مشتق دوم
print("Second derivative (d^2y/dx^2):", x.grad)

First derivative (dy/dx): tensor(12., grad_fn=<CopyBackwards>)
Second derivative (d^2y/dx^2): tensor(0., grad_fn=<ZeroBackward0>)


/usr/local/lib/python3.10/dist-packages/torch/autograd/graph.py:825: UserWarning: Using backward() with create_graph=True will create a reference cycle between the parameter and its gradient which can cause a memory leak. We recommend using autograd.grad when creating the graph to avoid this. If you have to use this function, make sure to reset the .grad fields of your parameters to None after use to break the cycle and avoid the leak. (Triggered internally at ../torch/csrc/autograd/engine.cpp:1201.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass


# محاسبه چندمتغیره


In [21]:
import torch

# تعریف متغیرها
x = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(2.0, requires_grad=True)

# تعریف تابع
z = x**2 + y**3 + x * y

# محاسبه گرادیان‌ها
z.backward()

# چاپ گرادیان‌ها
print("dz/dx:", x.grad)
print("dz/dy:", y.grad)

dz/dx: tensor(4.)
dz/dy: tensor(13.)


# مشتق در رگرسیون

In [22]:
# داده‌های آموزشی
x_train = torch.tensor([[1.0], [2.0], [3.0]], requires_grad=False)
y_train = torch.tensor([[2.0], [4.0], [6.0]], requires_grad=False)

# وزن‌ها و بایاس (قابل بهینه‌سازی)
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

# حلقه آموزش
learning_rate = 0.01
for epoch in range(100):
    # پیش‌بینی
    y_pred = w * x_train + b

    # تابع هزینه (MSE)
    loss = ((y_pred - y_train) ** 2).mean()

    # محاسبه گرادیان‌ها
    loss.backward()

    # به‌روزرسانی وزن‌ها
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    # صفر کردن گرادیان‌ها
    w.grad.zero_()
    b.grad.zero_()

    # نمایش خطا در هر چند مرحله
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}, w: {w.item()}, b: {b.item()}")

Epoch 0, Loss: 4.666666507720947, w: 1.09333336353302, b: 0.03999999910593033
Epoch 10, Loss: 0.46107372641563416, w: 1.612234354019165, b: 0.25782933831214905
Epoch 20, Loss: 0.05983422324061394, w: 1.7749229669570923, b: 0.31920844316482544
Epoch 30, Loss: 0.020879948511719704, w: 1.8276315927505493, b: 0.3324495851993561
Epoch 40, Loss: 0.01645718701183796, w: 1.846343755722046, b: 0.3309720456600189
Epoch 50, Loss: 0.015356030315160751, w: 1.8545070886611938, b: 0.3250848352909088
Epoch 60, Loss: 0.01460317987948656, w: 1.8593584299087524, b: 0.31796619296073914
Epoch 70, Loss: 0.013913922943174839, w: 1.8631324768066406, b: 0.31059351563453674
Epoch 80, Loss: 0.013259717263281345, w: 1.8665199279785156, b: 0.3032655715942383
Epoch 90, Loss: 0.01263656560331583, w: 1.8697351217269897, b: 0.2960716187953949


# جلوگیری از محاسبات گرادیان

In [23]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

# محاسبه با ردیابی گرادیان
y = x ** 2
print("With grad tracking:", y)

# محاسبه بدون ردیابی گرادیان
with torch.no_grad():
    y_no_grad = x ** 2
    print("Without grad tracking:", y_no_grad)

With grad tracking: tensor([1., 4., 9.], grad_fn=<PowBackward0>)
Without grad tracking: tensor([1., 4., 9.])


#  پاک کردن گرادیان‌ها

In [24]:
x = torch.tensor(2.0, requires_grad=True)

# اولین محاسبه
y = x ** 2
y.backward()
print("Gradient after first backward:", x.grad)

# پاک کردن گرادیان‌ها
x.grad.zero_()

# محاسبه دوم
z = x ** 3
z.backward()
print("Gradient after second backward:", x.grad)

Gradient after first backward: tensor(4.)
Gradient after second backward: tensor(12.)


# محاسبات با تنسورهای چند بعدی

In [27]:
# تعریف یک تنسور 2 بعدی
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)
print(x)

# تعریف یک تابع روی این تنسور
y = x ** 2 + 3 * x

# مجموع عناصر y
z = y.sum()
print(z)

# محاسبه گرادیان (dz/dx)
z.backward()

# گرادیان را چاپ می‌کنیم
print("Gradient of z with respect to x:")
print(x.grad)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor(60., grad_fn=<SumBackward0>)
Gradient of z with respect to x:
tensor([[ 5.,  7.],
        [ 9., 11.]])
